version: "3.1"
services:
  db:
    image: postgres:11
    restart: always
    volumes:
      - ./docker-data/db-data:/var/lib/postgresql/data
      - ./scripts/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080
  web:
    image: golang:1.13
    restart: always
    links: 
      - "db:db"
    depends_on: 
      - db
    build: .
    ports:
      - 8080:8080
